### PR TITLE
Added return process instance to monitor processes

### PR DESCRIPTION
**Pull request by automation-stack**
If you need to control the running process is convenient to return it to the instance when the process starts

### CODE REVIEW

**Comment by jorangreef** [comment]
Thanks @automation-stack 

I can't accept the request, as it only returns the first speculative sudo call, but often the real process will be run later asynchronously.

**Comment by automation-stack** [comment]
But in this case, at least it has the opportunity to complete the process group timeout and process stdout / stder / stdin. How it can be done without returning anything?

**Comment by jorangreef** [comment]
It's not really possible without changing the way we run commands.

Currently we:

1. Try and run the command using sudo -n. If the sudo timestamp is already set, the command will execute, but there is no way to know ahead of time if we have the sudo timestamp until the command actually executes. If the sudo timestamp is not set, then sudo will not run the command and will return an error (we then proceed to step 2). This is what your pull request is returning.

2. If step 1 fails, we launch a prompt, and wait asynchronously and indefinitely until the user accepts or cancels. Then we retry the sudo -n command. This is what your pull request is missing.

The problem with returning any of the sudo -n commands is that your process would not know if an error relates to the command failing, or whether it relates to the sudo timestamp not being set. sudo-prompt might also try the sudo -n command several times.

We could try and make sudo-prompt more complicated to find out whether we have the timestamp (and return the process to you if we do), by running a dud command with sudo -n to check if the timestamp is set or not. Then we could use an asynchronous options.onProcessStarted callback to give you the process which we would start after finding out that the timestamp is set. But this is prone to race conditions. For example, any other process on the system might kill the timestamp just after we check it and then we would be returning a failed process (but we might launch another process after this which would succeed).

It's also not an option to add the dud check, since this would really slow sudo-prompt down when many commands are pending on a prompt. You would essentially be launching twice as many shells as would be needed.

So, possibly we could add an options.onAnyProcessStarted callback that might be called several times, with no guarantees as to whether the command will execute or whether sudo will fail and still require a prompt. It needs to be an asynchronous option. It's not exactly the same as child_process.exec in this way and I don't think it can be made to be (since we might launch the process several times to get it executed in the end).

**Comment by jorangreef** [comment]
Just to note that stdout / stderr are already buffered and passed to the final callback:
```
function(error, stdout, stderr) {}
```
We should update the docs to make this more clear.

**Comment by automation-stack** [comment]
OK, I understand that, but for long-running processes actually get a grip on events and to kill the process if it is delayed, for example. 

 How do you feel about this decision?

```js
var Node = {
....
  execParentProcess: null
};
.... 

function attempt(attempts, command, options, end) {
  ....
  cp = Node.child.exec('/usr/bin/sudo -n ' + command,
    ....
  );
  Node.execParentProcess = cp;
}
...

module.exports.getParent = function() {
    return Node.execParentProcess;
};
```

In this case, at the right time we can to get control over the current parent process (sudo) and manage this process group.

**Comment by jorangreef** [comment]
Thanks for the examples.

What would happen if two or three concurrent `sudo.exec` calls were issued? What should `sudo.getParent()` return then?

I would prefer to have a callback option passed in to the exec call. This is functional and does not rely on a global variable so it side-steps alot of bugs.

**Comment by automation-stack** [comment]
But the callback option is not able to control the process, ```sudo.getProcesses()``` may be an array contains all process instances. This will allow flexibility to manage running processes.
How do you think?

**Comment by jorangreef** [comment]
Why is the callback option not able to control the process? By callback, I don't mean the final callback but an additional onProcess callback passed as an option to the sudo exec call.

**Comment by jorangreef** [comment]
I don't want to add a global state variable as I already mentioned.

**Comment by automation-stack** [comment]
OK, it is clear that the use of global variables very bad pattern (with rare exceptions), but we can only use option like this
```js
....
function attempt(attempts, command, options, end, control) {
  ....
  control(Node.child.exec('/usr/bin/sudo -n ' + command,
    ....
  ));
}

....
function exec() {
  ....
  attempt(0, command, options, end, control);
}

// Calling component use something like this
....
sudo.exec('cmd', options, 
    function(err, stdout, stderr) {
        // some processing on process end
    },
    function(ps) {
        ps.stdout.on('data', function() {});
        setTimeout(function() {
            kill(ps.pid, 'SIGKILL', function(err) {
                // some processing
            });
        }.bind(ps), 50000);
    },
)
```

Ok?

**Comment by automation-stack** [comment]
Can i do new pull request?

**Comment by jorangreef** [comment]
Thanks, I will make the change directly. It's going to be a callback on options though, not an extra argument after the final callback, but otherwise exactly like that.

**Comment by jorangreef** [comment]
Added in https://github.com/jorangreef/sudo-prompt/commit/f91a0a9b16fd77f14a63b63ee5aeb581e288cc43

**Pull request closed without merging**
